# Questions, concerns, ideas, etc, please use the ticket system, comments, or PM me on BukkitDev
#  http://dev.bukkit.org/bukkit-plugins/ctt/
# 
# Separate gold block ids with commas
# Time limit and spawn delay is in seconds
# If continuous-games is true, games will reset with the players kept in game
#  If false, it will kick them back to the spawn as if they left
# For the kill message, colors can be added using ^ followed by the standard color code
#  Codes are found here: http://minecraft.gamepedia.com/Formatting_codes
#  Example: ^4 - This will produce Dark Red
# Stats query the database every so often (more players = more queries)
#  If you don't want your database queried as much, disable stats
# If update-check is true, the plugin will check BukkitDev for an update every once per hour
#  Anyone with ctt.update as a permission will be notified when they login to the server when there is an update
# SQL option is either SQLite or MySQL
# 
# Kits with the permission ctt.kit will be randomly selected from when a player joins a game
# Kits with the permission ctt.kit.x, where x is anything, can only be picked by a player with
#  the permission ctt.kit.x
# Kits are selected through commands, so make the name of the kit easy and with NO SPACES!!!
#  Recommendation: Use a sign command plugin to allow players to use signs at spawn to choose kits
# The syntax for the contents is ID;AMOUNT;DURABILITY
#  Note: amount and durability are not required to be given
gold-block-ids: 49, 7
debug: false
time-limit: 180
max-players: 10
spawn-delay: 5
continuous-games: false
friendly-fire: false
kill-message: '^4%killer% ^6has killed ^4%victim%'
enable-stats: true
update-check: true
sql: SQLite
MySQL:
    hostname: 'localhost'
    port: '3306'
    database: 'CTT'
    username: 'minecraft'
    password: 'notch'
kits:
    Warrior:
        permission: ctt.kit
        contents: 285, 260;5, 397;1;4, 278
    Archer:
        permission: ctt.kit
        contents: 261, 262;64
    Runner:
        permission: ctt.kit.run
        contents: 267, 373;3;8226
