# Questions, concerns, ideas, etc, please use the ticket system, comments, or PM me on BukkitDev
#  http://dev.bukkit.org/bukkit-plugins/ctt/

# The ID numbers of blocks that gold blocks can be placed on (can always place on other gold blocks)
gold-block-ids: 49, 7

debug: false
 
# The time limit for games, in seconds
time-limit: 180
 
# The max amount of players in one game
max-players: 10
 
# The message displayed when a player is killed
# Colors can be added by using ^ followed by the standard color code
#  Codes are found here: http://minecraft.gamepedia.com/Formatting_codes
#  Example: ^4 - This will produce Dark Red
# Use %killer% for the killer's name, and %victim% for the victim's name
kill-message: '%killer% has crucified %victim%
 
# Stats do not query the database too much, however, the more players, the more queries
# Only when a player's stats have been changed will this plugin query the database about it
# Queries are handled on a separate thread, so they will not slow the server unless it's running full capacity
# To disable, set this to false
enable-stats: true
 
# SQLite is a local, fast database
# MySQL is on a server, usually remote, and may have a ping lag to it
# For local SQLite, set 'sql' equal to 'SQLite'.
# For remote or local MySQL, set 'sql' equal to 'MySQL' and set the MySQL options accordingly.
sql: SQLite
MySQL:
    hostname: 'localhost'
    port: '3306'
    database: 'CTT'
    username: 'minecraft'
    password: 'notch'
